//! Guard the generated bun console rather than build it.
//!
//! This used to shell out to the bundler when dist/ was missing, which
//! deadlocks the parent cargo lock and silently embeds a stale console.
//! scripts/check.sh and scripts/release.sh both build ui/dist before
//! touching this crate. If dist/ is missing or older than its inputs, say
//! so and stop. Never invoke bun or scripts/build-ui.sh from here.
//! Dist files are copied into `$OUT_DIR/ui_embed` and included by a path
//! relative to the generated file: an absolute `include_bytes!` leaves
//! the workspace path in the binary, and `--remap-path-prefix` does not
//! rewrite it.

use std::fs;
use std::io::Write;
use std::path::{Path, PathBuf};
use std::time::SystemTime;

fn main() {
    let manifest = PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR"));
    let root = manifest.join("../..");
    let dist = root.join("ui/dist");
    let index = dist.join("index.html");

    let inputs = [
        root.join("ui/src"),
        root.join("ui/index.html"),
        root.join("ui/package.json"),
        root.join("ui/bun.lock"),
        root.join("ui/bunfig.toml"),
        root.join("ui/fonts"),
        root.join("scripts/build-ui.sh"),
    ];
    println!("cargo:rerun-if-changed={}", dist.display());
    for path in &inputs {
        println!("cargo:rerun-if-changed={}", path.display());
        emit_rerun(path);
    }

    if !dist.is_dir() || !index.is_file() {
        panic!("missing ui/dist — run scripts/build-ui.sh (or scripts/check.sh ui) first");
    }

    let mut files: Vec<(String, PathBuf)> = Vec::new();
    collect_files(&dist, "", &mut files);
    if files.iter().all(|(rel, _)| rel != "index.html") {
        panic!(
            "missing ui/dist/index.html — run scripts/build-ui.sh (or scripts/check.sh ui) first"
        );
    }
    for (_, path) in &files {
        println!("cargo:rerun-if-changed={}", path.display());
    }

    // index.html is rewritten every bun build. Copied fonts keep their
    // source mtimes (`cp -a`), so they must not stamp the bundle.
    let built = newest(&index);
    for path in &inputs {
        let changed = newest(path);
        if changed > built {
            panic!(
                "ui/dist is older than {} — run scripts/build-ui.sh \
                 (or scripts/check.sh ui) to rebuild the console",
                path.display()
            );
        }
    }

    let out_dir = PathBuf::from(std::env::var("OUT_DIR").expect("OUT_DIR"));
    let embed_dir = out_dir.join("ui_embed");
    if embed_dir.exists() {
        fs::remove_dir_all(&embed_dir).expect("clear ui_embed");
    }
    fs::create_dir_all(&embed_dir).expect("ui_embed");
    for (rel, path) in &files {
        refuse_rel(rel);
        let dest = embed_dest(&embed_dir, rel);
        if let Some(parent) = dest.parent() {
            fs::create_dir_all(parent).expect("ui_embed parent");
        }
        fs::copy(path, &dest)
            .unwrap_or_else(|e| panic!("copy {} -> {} ({e})", path.display(), dest.display()));
    }

    let out = out_dir.join("ui_assets.rs");
    let mut gen = fs::File::create(&out).expect("ui_assets.rs");
    writeln!(
        gen,
        "// @generated by crates/secd-web/build.rs from ui/dist. Do not edit.\n"
    )
    .expect("write");
    writeln!(gen, "pub static ASSETS: &[(&str, &[u8])] = &[").expect("write");
    for (rel, _) in &files {
        writeln!(
            gen,
            "    ({}, include_bytes!({})),",
            rust_string_lit(rel),
            rust_string_lit(&format!("ui_embed/{rel}"))
        )
        .expect("write");
    }
    writeln!(gen, "];\n").expect("write");
    writeln!(gen, "pub static ASSET_PATHS: &[&str] = &[").expect("write");
    for (rel, _) in &files {
        if rel == "index.html" {
            continue;
        }
        writeln!(gen, "    {},", rust_string_lit(&format!("/{rel}"))).expect("write");
    }
    writeln!(gen, "];").expect("write");
}

fn emit_rerun(path: &Path) {
    if !path.is_dir() {
        return;
    }
    let Ok(entries) = fs::read_dir(path) else {
        return;
    };
    for entry in entries.filter_map(Result::ok) {
        let p = entry.path();
        println!("cargo:rerun-if-changed={}", p.display());
        if p.is_dir() {
            emit_rerun(&p);
        }
    }
}

fn collect_files(dir: &Path, prefix: &str, out: &mut Vec<(String, PathBuf)>) {
    let mut entries: Vec<_> = fs::read_dir(dir)
        .unwrap_or_else(|e| panic!("read {} ({e})", dir.display()))
        .filter_map(Result::ok)
        .collect();
    entries.sort_by_key(|e| e.file_name());
    for entry in entries {
        let name = entry.file_name();
        let name = name.to_string_lossy();
        if name.starts_with('.') {
            continue;
        }
        let rel = if prefix.is_empty() {
            name.into_owned()
        } else {
            format!("{prefix}/{name}")
        };
        let path = entry.path();
        if path.is_dir() {
            collect_files(&path, &rel, out);
        } else if path.is_file() {
            refuse_rel(&rel);
            out.push((rel, path));
        }
    }
}

fn refuse_rel(rel: &str) {
    if rel.is_empty() || rel.starts_with('/') || rel.contains('\\') {
        panic!("rel paths must be relative with / separators: {rel}");
    }
    if rel.contains("..") {
        panic!("refusing ui/dist relative path containing ..: {rel}");
    }
}

fn embed_dest(embed_dir: &Path, rel: &str) -> PathBuf {
    let mut dest = embed_dir.to_path_buf();
    for part in rel.split('/') {
        dest.push(part);
    }
    dest
}

fn rust_string_lit(s: &str) -> String {
    let mut out = String::from("\"");
    for c in s.chars() {
        match c {
            '\\' => out.push_str("\\\\"),
            '"' => out.push_str("\\\""),
            _ => out.push(c),
        }
    }
    out.push('"');
    out
}

/// Newest mtime at or under `path`. Missing paths sort oldest.
fn newest(path: &Path) -> SystemTime {
    let Ok(meta) = fs::metadata(path) else {
        return SystemTime::UNIX_EPOCH;
    };
    if !meta.is_dir() {
        return meta.modified().unwrap_or(SystemTime::UNIX_EPOCH);
    }
    let Ok(entries) = fs::read_dir(path) else {
        return SystemTime::UNIX_EPOCH;
    };
    entries
        .filter_map(Result::ok)
        .map(|e| newest(&e.path()))
        .max()
        .unwrap_or(SystemTime::UNIX_EPOCH)
}
